version: '3.7'
services:
        kafka:  
                image: confluentinc/cp-kafka:latest
                ports:
                        - "9092:9092"
                environment:
                        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
                        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092 
                        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 
                        - KAFKA_BROKER_ID=2
                depends_on:
                        - zookeeper
                volumes:
                        - "./starters/:/tmp"
        rabitmq:
                image: rabbitmq:latest
        consul:
                image: consul:latest
        zookeeper:
                image: zookeeper:latest
        starter:
                build: ./starters/.
                entrypoint: /usr/bin/wait-for-it.sh kafka:29092 -t 60 -- /usr/bin/kafka_start.sh
                depends_on:
                        - kafka
                links:
                        - zookeeper

